name: mpv

permissions:
  contents: write

on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  mpv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: portable_config

      - name: Download mpv
        uses: robinraju/release-downloader@v1
        with:
          repository: zhongfly/mpv-winbuild
          latest: true
          fileName: "mpv-x86_64-20*-git-*.7z"

      - name: Get the filename of the mpv archive
        id: mpv-filename
        run: |
          echo "fullname=$(ls | grep mpv)" >> $GITHUB_OUTPUT
          echo "basename=$(ls | grep mpv | xargs -I {} basename {} .7z)" >> $GITHUB_OUTPUT
          echo "commit=$(ls | grep -oP '(?<=git-)[0-9a-fA-F]+')" >> $GITHUB_OUTPUT

      - name: Extract mpv archive
        run: 7z x ${{ steps.mpv-filename.outputs.fullname }} -o${{ steps.mpv-filename.outputs.basename }}

      - name: Copy portable config to the extracted mpv folder
        run: cp -r "portable_config" "${{ steps.mpv-filename.outputs.basename }}/portable_config"

      - name: Remove the original mpv archive
        run: rm ${{ steps.mpv-filename.outputs.fullname }}

      - name: Compress mpv using 7zip
        run: 7z a ${{ steps.mpv-filename.outputs.fullname }} \
          ${{ steps.mpv-filename.outputs.basename }} \
          -t7z -m0=lzma2 -mx9 -mfb=273 -md=1024m -ms=on -mmt=on

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: mpv
          artifacts: ${{ steps.mpv-filename.outputs.fullname }}
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true
          makeLatest: true
          tag: mpv
          body: >
            Pre-configured portable MPV based on [zhongfly's build](https://github.com/zhongfly/mpv-winbuild) using
            flower's config.

            This release is updated daily using [this workflow](https://github.com/${{ github.repository }}/blob/master/.github/workflows/mpv.yml)

            Based on: mpv-player/mpv@${{ steps.mpv-filename.outputs.commit }}

            Logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}