name: mpv

permissions:
  contents: write

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  push:
    paths:
      - "portable_config/**"

jobs:
  check:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check.outputs.skip }}
    steps:
      - name: Check for new mpv commit
        id: check
        run: |
          set -e
          latest_commit=$(curl -s https://api.github.com/repos/mpv-player/mpv/commits/master | jq -r .sha | cut -c1-7)
          echo "latest_commit=$latest_commit" >> $GITHUB_OUTPUT
          echo "Upstream mpv commit: $latest_commit"

          last_release_commit=$(gh release view mpv --repo "${{ github.repository }}" --json body -q .body | grep -oP '(?<=mpv-player/mpv@)[0-9a-fA-F]+' || echo "none")
          echo "Last release commit: $last_release_commit"

          if [ "$latest_commit" = "$last_release_commit" ]; then
            echo "No new mpv commits found."
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "New mpv commit detected."
            echo "skip=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ github.token }}

  build:
    needs: check
    if: needs.check.outputs.skip == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: portable_config

      - name: Download mpv
        uses: robinraju/release-downloader@v1
        with:
          repository: zhongfly/mpv-winbuild
          latest: true
          fileName: "mpv-x86_64-20*-git-*.7z"

      - name: Get the filename of the mpv archive
        id: mpv-filename
        run: |
          echo "fullname=$(ls | grep mpv)" >> $GITHUB_OUTPUT
          echo "basename=$(ls | grep mpv | xargs -I {} basename {} .7z)" >> $GITHUB_OUTPUT
          echo "commit=$(ls | grep -oP '(?<=git-)[0-9a-fA-F]+')" >> $GITHUB_OUTPUT

      - name: Extract mpv archive
        run: 7z x ${{ steps.mpv-filename.outputs.fullname }} -o${{ steps.mpv-filename.outputs.basename }}

      - name: Copy portable config to the extracted mpv folder
        run: cp -r "portable_config" "${{ steps.mpv-filename.outputs.basename }}/portable_config"

      - name: Remove the original mpv archive
        run: rm ${{ steps.mpv-filename.outputs.fullname }}

      - name: Compress mpv using 7zip
        run: 7z a ${{ steps.mpv-filename.outputs.fullname }} ${{ steps.mpv-filename.outputs.basename }} -mx9

      - name: Create release with mpv
        uses: ncipollo/release-action@v1
        with:
          name: mpv
          artifacts: ${{ steps.mpv-filename.outputs.fullname }}
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true
          makeLatest: true
          tag: mpv
          body: >
            Pre-configured portable MPV based on [zhongfly's build](https://github.com/zhongfly/mpv-winbuild) using
            flower's config.

            This release is updated daily using [this workflow](https://github.com/${{ github.repository }}/blob/master/.github/workflows/mpv.yml)

            Based on: mpv-player/mpv@${{ steps.mpv-filename.outputs.commit }}

            Logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

  portable-config:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compress portable_config
        run: 7z a portable_config.7z portable_config -mx9

      - name: Upload portable_config to mpv release
        uses: ncipollo/release-action@v1
        with:
          name: mpv
          artifacts: portable_config.7z
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true
          makeLatest: false
          tag: mpv
