name: mpv

permissions:
  contents: write

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  push:
    paths:
      - "portable_config/**"

jobs:
  build:
    runs-on: ubuntu-latest
    # Run always on push to portable_config, or on workflow_dispatch/schedule
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: portable_config

      - name: Check if we need to download new mpv (only on schedule/workflow_dispatch)
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        id: check
        run: |
          latest_commit=$(curl -s https://api.github.com/repos/mpv-player/mpv/commits/master | jq -r .sha | cut -c1-7)
          echo "latest_commit=$latest_commit" >> $GITHUB_OUTPUT

          last_release_commit=$(gh release view mpv --repo "${{ github.repository }}" --json body -q .body | grep -oP '(?<=mpv-player/mpv@)[0-9a-fA-F]+' || echo "none")
          if [ "$latest_commit" = "$last_release_commit" ]; then
            echo "skip_download=true" >> $GITHUB_OUTPUT
          else
            echo "skip_download=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Download mpv
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' && (steps.check.outputs.skip_download != 'true')
        uses: robinraju/release-downloader@v1
        with:
          repository: zhongfly/mpv-winbuild
          latest: true
          fileName: "mpv-x86_64-20*-git-*.7z"

      - name: Get the filename of the mpv archive
        id: mpv-filename
        run: |
          if ls mpv* 1> /dev/null 2>&1; then
            echo "fullname=$(ls | grep mpv)" >> $GITHUB_OUTPUT
            echo "basename=$(ls | grep mpv | xargs -I {} basename {} .7z)" >> $GITHUB_OUTPUT
            echo "commit=$(ls | grep -oP '(?<=git-)[0-9a-fA-F]+')" >> $GITHUB_OUTPUT
          else
            echo "fullname=" >> $GITHUB_OUTPUT
            echo "basename=mpv" >> $GITHUB_OUTPUT
            echo "commit=unknown" >> $GITHUB_OUTPUT
          fi

      - name: Extract mpv archive
        if: steps.mpv-filename.outputs.fullname != ''
        run: 7z x ${{ steps.mpv-filename.outputs.fullname }} -o${{ steps.mpv-filename.outputs.basename }}

      - name: Copy portable config to the extracted mpv folder
        run: cp -r "portable_config" "${{ steps.mpv-filename.outputs.basename }}/portable_config"

      - name: Remove the original mpv archive
        if: steps.mpv-filename.outputs.fullname != ''
        run: rm ${{ steps.mpv-filename.outputs.fullname }}

      - name: Compress mpv using 7zip
        run: 7z a mpv.7z ${{ steps.mpv-filename.outputs.basename }} -mx9

      - name: Compress portable_config separately
        run: 7z a portable_config.7z portable_config -mx9

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: mpv
          artifacts: mpv.7z, portable_config.7z
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true
          makeLatest: true
          tag: mpv
          body: >
            Pre-configured portable MPV based on [zhongfly's build](https://github.com/zhongfly/mpv-winbuild) using
            flower's config.

            This release is updated automatically using [this workflow](https://github.com/${{ github.repository }}/blob/master/.github/workflows/mpv.yml)

            Based on: mpv-player/mpv@${{ steps.mpv-filename.outputs.commit }}

            Logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
